language: node_js
node_js:
- 10.12.0

branches:
  # only:
  # - master
  # - /^greenkeeper/.*$/
  except:
  - gh-pages

install:
 - npm i -f
 - npm i -g codecov

script: 
 - npm run test
 - npm run report-coverage
 - codecov
 - npm run build

deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master
