language: node_js
node_js:
- 10.12.0

cache:
  yarn: true
  directories:
    - node_modules

branches:
  except:
    - gh-pages

install:
  - yarn install --force
  - yarn global add codecov

jobs:
  include:
    - stage: test
      name: "Test"
      script: yarn test
    - name: "Coverage"
      script: codecov
    - stage: build
      script: yarn build
    - stage: deploy
      name: "Deploy"
      script: skip
      deploy:
        local-dir: build
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true

stages:
  - name: test
  - name: pr_title_check
  - name: build
  - name: deploy
    on:
      branch: master
