export const GENERAL_UPDATE_CHARACTER_NAME = 'GENERAL_UPDATE_NAME'
export const GENERAL_UPDATE_EXPERIENCE_POINTS =
  'GENERAL_UPDATE_EXPERIENCE_POINTS'
export const GENERAL_UPDATE_LEVEL = 'GENERAL_UPDATE_LEVEL'
export const GENERAL_UPDATE_PLAYER_NAME = 'GENERAL_UPDATE_PLAYER_NAME'
export const GENERAL_UPDATE_RACE = 'GENERAL_UPDATE_RACE'
export const GENERAL_UPDATE_OTHER_PROF_AND_LANGUAGE =
  'GENERAL_UPDATE_OTHER_PROF_AND_LANGUAGE'
export const GENERAL_UPDATE_FEATURES_AND_TRAITS =
  'GENERAL_UPDATE_FEATURES_AND_TRAITS'
