const classes = {
  BARBARIAN: 'BARBARIAN',
  BARD: 'BARD',
  CLERIC: 'CLERIC',
  DRUID: 'DRUID',
  FIGHTER: 'FIGHTER',
  MONK: 'MONK',
  PALADIN: 'PALADIN',
  RANGER: 'RANGER',
  ROGUE: 'ROGUE',
  SORCERER: 'SORCERER',
  WARLOCK: 'WARLOCK',
  WIZARD: 'WIZARD'
}

export default classes
