const indexedItems = {
  ABILITY_SCORE: 'ABILITY_SCORE',
  CLASS: 'CLASS',
  CONDITIONS: 'CONDITIONS',
  DAMAGE_TYPES: 'DAMAGE_TYPES',
  EQUIPMENT: 'EQUIPMENT',
  EQUIPMENT_CATEGORIES: 'EQUIPMENT_CATEGORIES',
  FEATURES: 'FEATURES',
  LANGUAGES: 'LANGUAGES',
  LEVELS: 'LEVELS',
  MAGIC_SCHOOL: 'MAGIC_SCHOOL',
  PROFICIENCIES: 'PROFICIENCIES',
  RACES: 'RACES',
  SKILLS: 'SKILLS',
  SPELLCASTING: 'SPELLCASTING',
  SPELLS: 'SPELLS',
  SUBCLASSSES: 'SUBCLASSSES',
  SUBRACES: 'SUBRACES',
  TRAITS: 'TRAITS',
  WEAPON_PROPERTIES: 'WEAPON_PROPERTIES'
}
export default indexedItems
